In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import KNeighborsClassifier

In [4]:
# Import data from csv files

train = pd.read_csv(r'~/Documents/FALL2021/COMP551/Assignment1/comp551-p1/Adult/adult.csv')
test = pd.read_csv(r'~/Documents/FALL2021/COMP551/Assignment1/comp551-p1/Adult/adult-test.csv')

all_data = pd.concat([train, test], axis=0, sort=False)

train

39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse   
1      38            Private  215646      HS-grad    9             Divorced   
2      53            Private  234721         11th    7   Married-civ-spouse   
3      28            Private  338409    Bachelors   13   Married-civ-spouse   
4      37            Private  284582      Masters   14   Married-civ-spouse   
...    ..                ...     ...          ...  ...                  ...   
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40            Private  154374      HS-grad    9   Married-civ-spouse   
32557  58            Private  151910      HS-grad    9              Widowed   
32558  22            Private  201490      HS-grad    9        Never-married   
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

             Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0         Exec-managerial         Husband   White     Male      0   0   13   
1       Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2       Handlers-cleaners         Husband   Black     Male      0   0   40   
3          Prof-specialty            Wife   Black   Female      0   0   40   
4         Exec-managerial            Wife   White   Female      0   0   40   
...                   ...             ...     ...      ...    ...  ..  ...   
32555        Tech-support            Wife   White   Female      0   0   38   
32556   Machine-op-inspct         Husband   White     Male      0   0   40   
32557        Adm-clerical       Unmarried   White   Female      0   0   40   
32558        Adm-clerical       Own-child   White     Male      0   0   20   
32559     Exec-managerial            Wife   White   Female  15024   0   40   

        United-States   <=50K  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3                Cuba   <=50K  
4       United-States   <=50K  
...               ...     ...  
32555   United-States   <=50K  
32556   United-States    >50K  
32557   United-States   <=50K  
32558   United-States   <=50K  
32559   United-States    >50K  

[32560 rows x 15 columns]

In [8]:
train.sample(frac=0.5)

39          State-gov   77516      Bachelors   13        Never-married  \
864    24            Private  309055   Some-college   10        Never-married   
18087  47            Private  111961        HS-grad    9   Married-civ-spouse   
1580   31            Private  169104      Bachelors   13        Never-married   
18588  37            Private  238049            9th    5        Never-married   
29938  66       Self-emp-inc  102663        7th-8th    4   Married-civ-spouse   
...    ..                ...     ...            ...  ...                  ...   
14868  28            Private  214689      Bachelors   13        Never-married   
28011  35            Private   82552     Assoc-acdm   12   Married-civ-spouse   
18603  29                  ?  108775        HS-grad    9   Married-civ-spouse   
19371  32   Self-emp-not-inc  182691        HS-grad    9        Never-married   
12872  25            Private  181814        HS-grad    9        Never-married   

             Adm-clerical    Not-in-family                White     Male  \
864                 Sales    Not-in-family                White   Female   
18087       Other-service             Wife                Black   Female   
1580                Sales        Own-child   Asian-Pac-Islander     Male   
18588     Priv-house-serv    Not-in-family                White   Female   
29938     Exec-managerial          Husband                White     Male   
...                   ...              ...                  ...      ...   
14868   Handlers-cleaners   Other-relative                White     Male   
28011        Tech-support          Husband                White     Male   
18603                   ?          Husband                White     Male   
19371       Other-service        Unmarried                White     Male   
12872        Craft-repair   Other-relative                White   Female   

        2174   0   40        United-States   <=50K  
864        0   0   15        United-States   <=50K  
18087      0   0   30        United-States   <=50K  
1580       0   0   40                    ?   <=50K  
18588      0   0   30          El-Salvador   <=50K  
29938      0   0   50        United-States   <=50K  
...      ...  ..  ...                  ...     ...  
14868      0   0   25        United-States   <=50K  
28011      0   0   40        United-States   <=50K  
18603      0   0   40   Dominican-Republic   <=50K  
19371      0   0   60        United-States   <=50K  
12872      0   0   40        United-States   <=50K  

[16280 rows x 15 columns]

In [11]:
def train_valid_split_CV(df, label_columns: list, frac=1, k=5):
    """
    Generator for k-fold cross validation.
    
    :param df: the dataframe containing the training and validation data
    :param label_columns: columns corresponding to the labels
    :param frac: fraction of the dataframe which should be used
    :param k: number of split in the cross validation
    :return: a tuple containing the training and validation data
    """
    # shuffle keep only a fraction of the entire dataframe    
    df = df.sample(frac=frac)
    split = np.array_split(df, k)
    for i in range(k):
        training_data = pd.concat([split[j] for j in range(k) if j != i], axis=0, sort=False)
        X_train = np.array(training_data.drop(label_columns), axis=1)
        Y_train = np.array(training_data[label_columns])
        
        validation_data = split[i]
        X_valid = np.array(validation_data.drop(label_columns), axis=1)
        Y_valid = np.array(validation_data[label_columns])
        
        yield X_train, X_valid, Y_train, Y_valid

In [17]:
for frac in [0.3, 0.5]:
    for train, valid in cross_validation_generator(train):
        model.fit(train)
        model.predict(valid)

       39          State-gov   77516      Bachelors   13        Never-married  \
23875  54        Federal-gov  332243           12th    8   Married-civ-spouse   
14112  36            Private  181589      Bachelors   13        Never-married   
20649  48            Private  216214           11th    7   Married-civ-spouse   
27904  36            Private  179488   Some-college   10             Divorced   
16914  30          Local-gov   44566      Bachelors   13   Married-civ-spouse   
...    ..                ...     ...            ...  ...                  ...   
6714   40            Private  229148           12th    8   Married-civ-spouse   
9083   56            Private  139616      Bachelors   13             Divorced   
13490  21            Private  185357        HS-grad    9        Never-married   
27744  36   Self-emp-not-inc  239415        HS-grad    9   Married-civ-spouse   
32309  21                  ?  205939   Some-college   10        Never-married   

             Adm-clerical  

       39          State-gov   77516      Bachelors   13        Never-married  \
20706  20   Self-emp-not-inc  188274   Some-college   10        Never-married   
14808  55            Private  195329        HS-grad    9              Widowed   
8392   50       Self-emp-inc  119099   Some-college   10   Married-civ-spouse   
18780  47          Local-gov  148576    Prof-school   15   Married-civ-spouse   
3337   79                  ?  144533        HS-grad    9              Widowed   
...    ..                ...     ...            ...  ...                  ...   
4414   38   Self-emp-not-inc  357962            9th    5             Divorced   
26543  43            Private  216497      Bachelors   13             Divorced   
22763  44            Private  109273   Some-college   10        Never-married   
29537  22            Private   32616   Some-college   10        Never-married   
32287  21            Private   67804            9th    5        Never-married   

             Adm-clerical  

In [8]:
test_df = pd.DataFrame(data={'food': ['Burger', 'hotdog', 'hotdog', 'Burger', 'Cheese', 'hotdog'],
                            'color': ['red', 'blue', 'blue', 'red', 'blue', 'blue']})

In [9]:
test_df.shape[1]

2

In [10]:
ohe = OneHotEncoder(sparse=False)
ohe_arr = ohe.fit_transform(test_df)

In [11]:
ohe_arr

array([[1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.]])

In [4]:
arr = np.array(
      [[[1., 0., 0.],[ 0., 1.]],
       [[0., 0., 1.],[ 1., 0.]],
       [[0., 0., 1.],[ 1., 0.]],
       [[1., 0., 0.],[ 0., 1.]],
       [[0., 1., 0.],[ 1., 0.]],
       [[0., 0., 1.],[ 1., 0.]]], dtype=object)

In [66]:
for feature_number in range(test_df.shape[1]):
    print([f for f in ohe.get_feature_names() if f'{feature_number}' in f])

['x0_Burger', 'x0_Cheese', 'x0_hotdog']
['x1_blue', 'x1_red']


In [43]:
for row in ohe_arr:
    print(row)
    print(''.join(str(int(b)) for b in row))
    
def encoding_as_str(matrix):
    res = [''.join(str(int(b)) for b in row) for row in matrix]
    return 'res', res
    
encoding_as_str(ohe_arr)

[1. 0. 0.]
100
[0. 0. 1.]
001
[0. 0. 1.]
001
[1. 0. 0.]
100
[0. 1. 0.]
010
[0. 0. 1.]
001


('res', ['100', '001', '001', '100', '010', '001'])

In [15]:
df = test_df.join(pd.DataFrame(data=ohe_arr, columns=ohe.get_feature_names()))

In [51]:
df

food  x0_Burger  x0_Cheese  x0_hotdog
0  Burger        1.0        0.0        0.0
1  hotdog        0.0        0.0        1.0
2  hotdog        0.0        0.0        1.0
3  Burger        1.0        0.0        0.0
4  Cheese        0.0        1.0        0.0
5  hotdog        0.0        0.0        1.0

In [59]:
df[[f for f in ohe.get_feature_names() if '0' in f]].values.tolist()

[[1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0],
 [1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0]]

In [53]:
pd.DataFrame(data=ohe_arr)# , columns=ohe.get_feature_names())

0    1    2    3    4
0  1.0  0.0  0.0  0.0  1.0
1  0.0  0.0  1.0  1.0  0.0
2  0.0  0.0  1.0  1.0  0.0
3  1.0  0.0  0.0  0.0  1.0
4  0.0  1.0  0.0  1.0  0.0
5  0.0  0.0  1.0  1.0  0.0

In [25]:
s = '00010'
l = [c for c in s]

In [26]:
l

['0', '0', '0', '1', '0']

In [28]:
"".join(l)

'00010'

In [70]:
for feature_number in range(test_df.shape[1]):
    print(df[[f for f in ohe.get_feature_names() if f'{feature_number}' in f]])

   x0_Burger  x0_Cheese  x0_hotdog
0        1.0        0.0        0.0
1        0.0        0.0        1.0
2        0.0        0.0        1.0
3        1.0        0.0        0.0
4        0.0        1.0        0.0
5        0.0        0.0        1.0


KeyError: "None of [Index(['x1_blue', 'x1_red'], dtype='object')] are in the [columns]"

In [5]:
arr = np.array(
      [[[1., 0., 0.],[ 0., 1.]],
       [[0., 0., 1.],[ 1., 0.]],
       [[0., 0., 1.],[ 1., 0.]],
       [[1., 0., 0.],[ 0., 1.]],
       [[0., 1., 0.],[ 1., 0.]],
       [[0., 0., 1.],[ 1., 0.]]], dtype=object)

In [6]:
arr

array([[list([1.0, 0.0, 0.0]), list([0.0, 1.0])],
       [list([0.0, 0.0, 1.0]), list([1.0, 0.0])],
       [list([0.0, 0.0, 1.0]), list([1.0, 0.0])],
       [list([1.0, 0.0, 0.0]), list([0.0, 1.0])],
       [list([0.0, 1.0, 0.0]), list([1.0, 0.0])],
       [list([0.0, 0.0, 1.0]), list([1.0, 0.0])]], dtype=object)

In [12]:
ohe_arr

array([[1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.]])

In [14]:
labels = np.array([0,0,1,1,0,0])

In [13]:
knn = KNeighborsClassifier(n_neighbors=5)

In [18]:
knn.fit(arr, labels)

ValueError: setting an array element with a sequence.

In [17]:
knn.predict([[1., 0., 0., 0., 1.]])

array([0])